app = "digital-banking-backend"
primary_region = "iad"

[build]
  # Uses Dockerfile in repo

[env]
  PORT = "3001"
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[deploy]
  release_command = "npx prisma migrate deploy --schema=./prisma/schema.prisma"


